steps:
  # Copy the service account key to the workspace
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://pucket-123/key/project-123-416205-f4c65ed9fb52.json', '/workspace/project-123-416205-f4c65ed9fb52.json']
  # Authenticate and set the project
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth activate-service-account --key-file=/workspace/project-123-416205-f4c65ed9fb52.json
        gcloud config set project project-123-416205
   # Log in to Docker with the service account for Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'docker login -u _json_key --password-stdin https://asia-south1-docker.pkg.dev < /workspace/project-123-416205-f4c65ed9fb52.json'
      # Build the Docker image using Dockerfile from the source repository
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/project-123-416205/artifact-123', '.'] # Assumes Dockerfile is in the root directory of the repository
